spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marinaaparicio/bootCamp-ConfigServer
          default-label: main
          search-paths:
          - '*.yaml'
              
server:
  port: 8888
